SELECT 
    c.name
FROM HOME_ASSIGNMENT.PUBLIC.TRANSFORMED_SALES_DATA s
JOIN HOME_ASSIGNMENT.PUBLIC.RAW_CUSTOMER_DATA c ON s.customer_id = c.id
WHERE s.order_year = 2023
GROUP BY c.id, c.name
ORDER BY SUM(s.total_sales_amount) DESC
LIMIT 5;